apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
  labels:
    app: urban-gardening
    component: certificate-issuer
    environment: production
    managed-by: cert-manager
    security-tier: infrastructure
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
    cert-manager.io/enable-certificate-owner-ref: "true"
spec:
  acme:
    # Production Let's Encrypt ACME server endpoint
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email for important account notifications
    email: security@urban-gardening.example.com
    # Secret to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    # Configure challenge solvers
    solvers:
      - http01:
          ingress:
            class: nginx
            podTemplate:
              spec:
                # Security hardening for solver pods
                nodeSelector:
                  kubernetes.io/os: linux
                securityContext:
                  runAsNonRoot: true
                  runAsUser: 1001
        # Selector to determine which Ingress objects this solver is applicable to
        selector:
          matchLabels:
            app: urban-gardening