apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: urban-gardening
  labels:
    app: urban-gardening
    tier: frontend
    component: web
    version: "1.0.0"
    managed-by: kubectl
data:
  # API Configuration
  VITE_API_BASE_URL: "/api/v1"
  VITE_API_TIMEOUT: "30000"  # 30 seconds in milliseconds
  
  # Authentication Settings
  VITE_AUTH_TOKEN_EXPIRY: "3600"  # 1 hour in seconds
  VITE_REFRESH_TOKEN_EXPIRY: "604800"  # 7 days in seconds
  
  # Application Metadata
  VITE_APP_NAME: "Urban Gardening Assistant"
  VITE_APP_VERSION: "1.0.0"
  VITE_NODE_ENV: "production"
  
  # Additional Frontend Settings
  VITE_ENABLE_CACHE: "true"
  VITE_CACHE_DURATION: "3600"  # 1 hour in seconds
  VITE_MAX_RETRY_ATTEMPTS: "3"
  VITE_RETRY_DELAY: "1000"  # 1 second in milliseconds