# Air configuration file for Urban Gardening Assistant backend services
# Version: 1.0.0

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "./"
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o ./tmp/app-tmp ./cmd/calculator/main.go ./cmd/cropmanager/main.go ./cmd/scheduler/main.go"

# Binary file yields from `cmd`.
bin = "./tmp/app-tmp"

# Customize binary.
full_bin = "./tmp/app-tmp"

# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "html"]

# Ignore these filename extensions or directories.
exclude_dir = ["assets", "tmp", "vendor", "test"]

# Watch these directories if you specified.
include_dir = []

# Exclude files.
exclude_file = []

# Exclude specific regular expressions.
exclude_regex = ["_test\\.go"]

# Exclude unchanged files.
exclude_unchanged = true

# Follow symlink for directories
follow_symlink = true

# This log file places in your tmp_dir.
log = "build-errors.log"

# Poll files for changes instead of using fsnotify.
poll = false

# Poll interval (defaults to 500ms)
poll_interval = 500 # ms

# Delay after each execution (defaults to 1000ms)
delay = 1000 # ms

# Stop running old binary when build errors occur.
stop_on_error = true

# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = false

# Delay after sending Interrupt signal
kill_delay = 500 # ms

[log]
# Show log time
time = true

# Only show main log (silences watcher, build, runner)
main_only = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[screen]
clear_on_rebuild = true
keep_scroll = true

[misc]
# Delete tmp directory on exit
clean_on_exit = true