apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: default
  labels:
    app: redis
    component: cache
    part-of: urban-gardening-assistant
spec:
  # Headless service for StatefulSet DNS-based discovery
  clusterIP: None
  ports:
    - port: 6379        # Standard Redis port
      targetPort: 6379  # Port on the pod
      name: redis       # Named port for easier reference
  selector:
    app: redis
    component: cache